### ISSUE TITLE
Feature: Change the speed of the sound

### ISSUE THREAD

**Issue by Guichaguri** [Guichaguri/TickrateChanger#1]
I think this has to be implemented, since the whole point of the mod is to change the speed of the **whole** game.

I think the way it should be implemented, is changing the pitch of the sounds.

**Comment by Guichaguri** [comment]
Added in 8dba27796e33a71d5878d18443535d2ebf585660

**Comment by Musikid-Official** [comment]
Was this implemented on the 1.8.9 release?
