### ISSUE TITLE
Can you make this mod for 1.16.3 Fabric?

### ISSUE THREAD

**Issue by bxvcd-732** [Guichaguri/TickrateChanger#10]
I really love this mod, but unfortunately it doesn't support newer versions. So, can you make this mod working on 1.16.3 Fabric or Forge?

**Comment by Xendergo** [comment]
You can use carpet mod to do the same thing, the command the change the tick rate is `/tick rate *tps*` and to slow down the game on the client, you can use `/carpet smoothClientAnimations true`

I'm not sure how well it works on servers tho

**Comment by bxvcd-732** [comment]
I found a similar mod for 1.16.3. Here it is: https://www.curseforge.com/minecraft/mc-mods/fabrictickrate-slow-motion-fast-forward
