### ISSUE TITLE
"Local tickrate"?

### ISSUE THREAD

**Issue by Frontrider** [Guichaguri/TickrateChanger#2]
It would be possible to change tickrate only in certain chunks?
I have less time to play, and I would need a tool like that to buy some time in my early game, on a server where I was a staff member.

**Comment by Guichaguri** [comment]
It is kind of possible, but it would require A LOT of tinkering in the Minecraft code and it would break most mods. So no, not going to happen.

You can update each entity/tileentity two or more times each tick, making it **look** faster, but that is not the objective of this mod. Sorry
