### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by sefldron** [Guichaguri/TickrateChanger#4]
Could you please update to 1.12.1? Really missing this one.

**Comment by cosmicdan** [comment]
I'll take a crack at updating to 1.12.2 and send a PR when done (may as well skip 1.12.1)

EDIT: The 1.12.2 version should also work on 1.12.1 because the only thing changed between current TickrateChanger and new Forge are the MCP mappings - which is the same between 1.12.1 and 1.12.2 currently.

EDIT2: Nevermind, it's not that simple it seems. Will make a build for both.

**Comment by cosmicdan** [comment]
Done. https://github.com/CosmicDan-Minecraft/TickrateChanger/releases/tag/1.0.13-ported

Note that these jars are unsigned and I think Forge needs signatures on Coremods these days. You'll have to sign them yourself.

**Comment by Guichaguri** [comment]
It's [out](https://minecraft.curseforge.com/projects/tickratechanger/files/2482684)! Thanks to @cosmicdan for the update :)

**Comment by sefldron** [comment]
Ugh. Official 1.12.1/1.12.2 only registered for 1.12.2
    Unsigned 1.12.1 version you linked to me was unrecognized. I don't know how to sign a jar.

**Comment by sefldron** [comment]
I look it up

**Comment by sefldron** [comment]
Derp! Did not realize that it was a jar in a zip... that one works. Not the official for 1.12.1

**Comment by cosmicdan** [comment]
@sefldron well there is no official for 1.12.1, it's only for 1.12.2 :) so just use my custom build until you update.

Both versions might work on either version but you need to set targetVersion annotation property for that to work, which is done in the code, but it's not important in this case.

Regardless, it shouldn't be long at all for people to update mods from 1.12.1 to 1.12.2.

**Comment by sefldron** [comment]
1.12.1 unsigned copy runs fine until then. I'll be ok until then. Hopefully I will have a better PC in a couple of months and then this will be for visual purpose only. eBay has a nice one for 450 I'm looking at. Took a lot to figure out how to run modded mc on a 15-271wm qc Pc integrated hd set smoothly enough with 107+ mods

**Comment by sefldron** [comment]
That's with an 8 render distance too so I'm pretty good at figuring this out I think

**Comment by sefldron** [comment]
On curse it says 1.12.1 compatible last Time I checked. Just saying

**Comment by Guichaguri** [comment]
@sefldron Sorry for that. [Here](https://minecraft.curseforge.com/projects/tickratechanger/files/2483406) is the 1.12.1 build
