### ISSUE TITLE
Uneffected timer

### ISSUE THREAD

**Issue by ShayBox** [Guichaguri/TickrateChanger#7]
Since you made this mod, I was wondering what would be the best way to make a "timer" that's unaffected by it, I'm currently using a `Timer`, but would something like counting the amount of ticks I receive from an event in a second and just not continuing with the code be a better idea? or something else I'm not thinking of

**Comment by Guichaguri** [comment]
It's tricky, depends on what you're trying to achieve. Relying on real-world time might work pretty well right out of the bat, but can cause all sorts of issues.
