### ISSUE TITLE
Is 1.13 a roadblock?

### ISSUE THREAD

**Issue by programing-monkey** [Guichaguri/TickrateChanger#9]
I would appreciate any information in regards to updating this mod past 1.13! To be clear I'm not asking for you to make an update for 1.13 (which if you can find the time would be amazing!) I'm just looking for any advice on making a quick and dirty 1.13 version for myself (and any others interested)!

**Comment by Guichaguri** [comment]
The mod is pretty small, shouldn't be too hard to update it
You have to update the build tools to Forge 1.13, then fix the compiler issues caused by the new version, and hope for the tick system to be unchanged, otherwise you'd probably have to rewrite the bytecode transformer stuff

**Comment by programing-monkey** [comment]
Thanks for the advice! It will be very useful as I've only ever tinkered with forge mods! lol
